# Generated by Django 4.0 on 2022-01-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
