# Generated by Django 4.0 on 2022-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='produce',
            name='image',
            field=models.ImageField(default='', upload_to='shop/image'),
        ),
        migrations.AddField(
            model_name='produce',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produce',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='produce',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
