# Generated by Django 4.0 on 2022-01-18 07:48
'''
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='shop/image')),
            ],
        ),
        migrations.DeleteModel(
            name='Produce',
        ),
    ]
'''
# Generated by Django 4.0 on 2022-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='produce',
            name='image',
            field=models.ImageField(default='', upload_to='shop/image'),
        ),
        migrations.AddField(
            model_name='produce',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produce',
            name='subcategory',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='produce',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
