# Generated by Django 4.0 on 2022-01-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
        ('shop', '0003_product_delete_produce'),
    ]

    operations = [
    ]
